spring:  
  # Database Configuration
  datasource:
    url: jdbc:mysql://db_chat:3306/organix?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    password: 'Chat@2025$'
    username: chat
    driver-class-name: com.mysql.cj.jdbc.Driver

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 604800000 # 7 days in milliseconds


application:
  uploads:
    path: /app/data
  backend:
    url: https://chat.appteste.info