spring:  
  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/organix?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: firewall
    driver-class-name: com.mysql.cj.jdbc.Driver

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 604800000 # 7 days in milliseconds
