spring:
  profiles:
    active: prod
  application:
    name: organix-backend
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update

  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: NON_NULL

# Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging Configuration
# logging:
  # level:
    #com.organixui.organixbackend: DEBUG
    #org.springframework.security: DEBUG
  #pattern:
    #console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

